### ISSUE TITLE
openvpn support

### ISSUE THREAD

**Issue by MCjorsh5** [chuangbo/hypro#2]
Can I use the local connection of the target to make a connection with an openvpn?

**Comment by chuangbo** [comment]
Sorry, I'm not sure I understand what you want.

**Comment by MCjorsh5** [comment]
forward port over openvpn please

**Comment by chuangbo** [comment]
If you already have established an OpenVPN connection from your local computer to a remote server, you can simply use a reverse proxy like nginx or caddy to forward HTTP connections.
